# Generated by Django 5.0.6 on 2024-06-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_persona_donador'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='direccion',
            field=models.TextField(default='Arequipa', max_length=30),
            preserve_default=False,
        ),
    ]
